### PR TITLE
Purebasic replace quick fix

### PR DESCRIPTION
**Pull request by ChrisRfr**
Quick fix for Replace German translation. 
And Translation added for Spanish and Italian.

### CODE REVIEW

**Comment by t-harter** [comment]
Looks like there is some encoding issue with the German version. Can you correct that?

**Comment by ChrisRfr** [comment]
Sorry, I'm not friends with GitHub, I'm afraid I'll do worse than better, so I prefer to leave it to you.
I am on Windows and I don't know the ANSI Unix format, I am just making the change Ersetzen => Replace, with Notepad or Beyond Compare, it looks good.  I save it and then I have encoding issues in GitGub desktop. I don't understand!

Alt text<br/>

**Comment by SicroAtGit** [comment]
@ChrisRfr You have saved the file `German/Editor.catalog` with the encoding `utf-8`, but it must be saved encoded as `iso-8859-1`.

It's a known problem: #154, #155

**Comment by tajmone** [comment]
> @ChrisRfr You have saved the file `German/Editor.catalog` with the encoding utf-8, but it must be saved encoded as iso-8859-1.

These "ASCII" vs Unicode encoding problems are starting to pile up, leading to the corruption of repository files; the issue should be solved at its root — and rather sooner than later.

Since "ASCII" mode has been dropped since PB 5.50, which also introduced support for UTF-8 files and strings conversion, there's really no good reason to use single-character encoded files for IDE settings or for other PB related tools (DocMaker, etc.).

Now that PB 6.0 is about to be released it would be a perfect time to fix these problems, switching to UTF-8 (with a BOM, if this simplifies compatibility).

This especially true for `.catalog` files, where the required single-char encoding could be different for different locales, and not necessarily Latin1/ISO-8859-1 — not to mention the encoding corruption problems that might creep in due to OS locale settings affecting the encoding of various tools, and the impossibility to validate single-char encoded files.

**Comment by ChrisRfr** [comment]
I tried a last attempt with notepad++ but it is still really confusing.
In npp, I convert "Deutsch\Editor.catalog" to ISO-8859-1, make the change and save it.
In GitHub desktop, I have a warning: line ending will be changed from LF to CRLF
and the + lines are displayed with the wrong encoding. 
I'm confused, only 7 characters to change. I'd rather leave the hand than do it wrong.
Switching to UTF-8 will help for sure.

Alt text<br/>

**Comment by SicroAtGit** [comment]
@tajmone Yes, the switch to UTF-8 should definitely be done very soon.

@ChrisRfr If you invite me to your repository, I can correct your branch.
See: [Inviting collaborators to a personal repository](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-user-account/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository)

**Comment by ChrisRfr** [comment]
Done, Thanks Alexander.

**Comment by SicroAtGit** [comment]
@ChrisRfr I have corrected your branch.
```console
$ file Deutsch/Editor.catalog --mime-encoding 
Deutsch/Editor.catalog: iso-8859-1
```

**Comment by ChrisRfr** [comment]
Thanks 🥇

**Comment by fantaisie-software** [comment]
> 

I just fixed the 2 files, should be good now.

**Comment by SicroAtGit** [comment]
@fantaisie-software Thanks, I have rebased the branch.

**Pull request merged**
