### PR TITLE
Remove Spaces in Files Names

### PR DESCRIPTION
**Pull request by tajmone**
Rename all files containing a space in their name, and amend references in Make files and markdown documents. 

See Issue #80 regarding this commit.

### CODE REVIEW

**Comment by SicroAtGit** [comment]
@tajmone your commit removes the file `PureBasicIDE/PureBasic IDE.pbp`

**Comment by tajmone** [comment]
> @tajmone your commit removes the file `PureBasicIDE/PureBasic IDE.pbp`

Completely forgot about the ignore rule! 

Manually force added the file and amended the commit!

Thanks for catching that.

**Comment by tajmone** [comment]
But I still think we shouldn't store PB project files in the repo, due to all the problems they cause to Git. We should enforce settings via compiler directive checks instead.

**Comment by kenmo-pb** [comment]
> But I still think we shouldn't store PB project files in the repo, due to all the problems they cause to Git. We should enforce settings via compiler directive checks instead.

@tajmone I like the suggestion before (was it you?) that the PBP file should become "PureBasicIDE.sample.pbp" or similar, for the user to copy and customize to their liking.

Also I've been working on 2 things related to this:

1. I've created 6 pre-defined targets in the PBP file (3 OS x 2 processors) with the proper extensions (exe, ico, icns) so you can simply choose your desired target (also Build All works!) The branch is already pushed here: https://github.com/fantaisie-software/purebasic/compare/master...kenmo-pb:cross-platform-targets
2. I'm implementing a "Source control mode" setting for projects, which prevents writing all the metadata that messes with Git (last open user, file fingerprints, computer name, view settings, etc.).

**Comment by tajmone** [comment]
@kenmo-pb , both features look promising. Can't wait to see them in place.

> @tajmone I like the suggestion before (was it you?) that the PBP file should become "PureBasicIDE.sample.pbp" or similar, for the user to copy and customize to their liking.

The problem there is deciding what to strip off from the proj. file (i.e. local info) and leave only the essential. I hadn't had time to dig into the `.pbp` file format and all its possible combinations (which is undocumented and need a trial and error approach to be "decoded", which is rather lengthy).

Ideally, stripping away non relevant data should be done via a script or PB tool.

**Comment by fantaisie-software** [comment]
I agree about stripping all user info off the .pbp (including MD5 hash check) and create a new file with those infos. That way we can easily share the .pbp project file on a git like repo

**Comment by kenmo-pb** [comment]
> I agree about stripping all user info off the .pbp (including MD5 hash check) and create a new file with those infos. That way we can easily share the .pbp project file on a git like repo

@fantaisie-software @t-harter This can be a later discussion (it won't be done for 5.72) :slightly_smiling_face: 

I have a work-in-progress but instead of saving 2 project files, it just... simply does not save that extra metadata. I have a list of what I've modified. The only functional loss so far is the "warn if files changed".

We can discuss further in issue #24 and I will push my version online soon.

**Comment by tajmone** [comment]
@fantaisie-software, could you please merge this PR?

**Comment by fantaisie-software** [comment]
Done

**Pull request merged**
