### PR TITLE
Fixed some issues

### PR DESCRIPTION
**Pull request by mk-soft-65**
AutoComplete:
- Fix RemoveKeyBoardShortcut constants #PB_Shortcut_*

macOS:
- Fix more ComboboxGadget background drawing

macOS Preference Compiler:
- Restart OpenFileRequester to open app packet folder 'Contents'

### CODE REVIEW

**Comment by mk-soft-65** [comment]
No found whitespaces on common.pb. 
But not any changes from me.

**Comment by HeX0R101** [comment]
Wouldn't it be better to let the PB team fix the ComboBox behaviour for MacOS in PB itself, instead of adding so many compiler directives to the PB IDE?

**Comment by mk-soft-65** [comment]
Maybe it's better.

But I will remove the many compilerIFs and do them via a macro.

**Comment by t-harter** [comment]
I am not the biggest fan of the "replace a PB command with a macro" trick. It can lead to hard to find bugs because it is simply not expected that a builtin command is not actually the original. Debugging something like that is really frustrating.

A better solution is to have a procedure named `ComboBoxGadgetSizeFix` or similar in all `XxxExtensions.pb` files which simply wraps `ComboBoxGadget()` for the OS where the fix is not needed. Then use this procedure everywhere in the code. This makes it much clearer what is going on when you read the code.

**Comment by mk-soft-65** [comment]
That may be correct, 
but it is a bug from ComboGadget in the macOS Gadget library or macOS framework and not in the PB IDE code. It should probably be fixed there. This way the customisation can be removed faster afterwards.

**Comment by t-harter** [comment]
It doesn't make much sense to me to have bugs in PB commands and then have workarounds for them in the official PB IDE. If there is a bug in a PB command it must be fixed there and not in the IDE at all.

Besides, who guarantees that it will be removed afterwards? If I know one thing about code maintenance it is that the bad hacks always live longer than expected and things that should just be temporary tend to be forgotten and left in the code. That goes double if it is actually invisible because it is hidden behind a macro. So you may just as well write code as if it were permanent.

**Comment by mk-soft-65** [comment]
I am goback to CompilerIf's

**Pull request closed without merging**
