### PR TITLE
Simplify build and final C cleanup

### PR DESCRIPTION
**Pull request by t-harter**
Now that the C dependencies are gone, we can greatly simplify the build setup because only a few preconditions remain and only a few environment variables need to be configured to run the makefiles. Most of these can actually be auto-detected. This PR removes the remaining C references and provides new and simplified build scripts:

- BuildEnv.cmd - for Windows
- BuildEnv.sh - for Linux and OSX

There is no need to edit these scripts anymore. All you need is call them with the target PB directory as an argument and the rest is configured automatically. See the content of the env scripts for details.

This PR also removes the `PB_BUILDTARGET` environment variable and stores all build files in a local `Build` directory which is not tracked by git. 

Preconditions for building are now rather simple:

- A PB installation (a separate install for IDE build and testing is recommended)
- UnixTools on Windows
- `make` and related tools on Linux/OSX

This should close the following: #38, #35, #24 (not 100% sure there)
The following issues should become obsolete by this: #32, #13

Some feedback on whether these scripts work right on various setups would be appreciated.

### CODE REVIEW

**Comment by tajmone** [comment]
> There are still a few makefiles that do not work directly with this setup. 

You should consider switching from Make to Rake. See this article by Martin Fowler:

https://martinfowler.com/articles/rake.html

Since I've adopted Rake all my builds have become easier to setup and I've been able to handle any custom task I need.

Make is such an outdated tool, whereas Rake can do so much more than Make, especially for cross-platform project.

**Comment by t-harter** [comment]
> So will it build in a local subfolder of the repo (my preference), or build and overwrite my existing PB IDE?

The IDE is still overwritten.

`PB_BUILDTARGET` used to specifiy a directory for temporary build files (compiled C sources, generated PB sources, stuff like that). The final executable was always created in the PB directory (specified via `PUREBASIC_HOME`). As such, the variable was always a bit ambiguous. I eliminated `PB_BUILDTARGET` and placed the temporary build files in a fixed subfolder of the repo. The final IDE is still copied into the PB directory. This directory has to be provided as parameter to the `BuildEnv.cmd` script.

The reason for copying the IDE into the PB directory is that you cannot test it properly otherwise. The IDE expects to be located in the PB directory and loads things like language files, themes, the compiler and other things relative to its own location. If you build it somewhere else you still have to put it somewhere resembling a PB directory to properly test it. Setting aside a dedicated PB installation to use both for compiling and as the test directory for the IDE is a simple way to solve this issue. I have worked this way on the IDE for years.

**Comment by kenmo-pb** [comment]
Thanks for clarification, I understand your reasons and usage.

In my own usage, I modified the build scripts to only write locally. As long as I have copied in `Scintilla.dll` I think the IDE basically works. The main reason for my modification: **the `makefile` would give me all sorts of permission/write errors trying to write to Program Files**, depending on what PC I was working on, Administrator mode, etc. I might have to make those changes again in this new branch!

**Comment by t-harter** [comment]
Why not just make a copy of your PureBasic directory somewhere else for IDE development? It does not take up that much space and you don't have to install anything. Just copy & paste your directory from Program Files to another location and you are good to go. It really can't get much simpler than that. If you start the IDE with /PORTABLE you won't even interfere with the settings of your regular install.

We could add something to .gitignore so you can copy the PB directory directly into your repository if you want to keep things in one place. This is not that much different from building locally and manually copying the needed files over to make the IDE run properly. We could even autodetect that case in `BuildEnv.cmd` so no argument will be needed.

**Comment by t-harter** [comment]
The change of directory should not be enforced in the `BuildEnv.cmd` script IMHO because the build environment is for building more things in the repository than just the IDE. However, you can easily achieve this yourself by running the script from your desired location. I do it by running `BuildEnv.cmd` from a shortcut that has the current directory specified the way I want it.

I added the pause commands.

About the tools: both these commands still appear in the IDE makefile (and some other makefiles too). So better keep the old version.

**Comment by ChrisRfr** [comment]
OK, Thanks for the explanations, on change directory PureBasicIDE and UnixTools for other makefiles
Just for being picky, it is preferable to use [cd /d %~dp0](https://ss64.com/nt/cd.html) rather than [cd %~dp0](https://stackoverflow.com/questions/18309941/what-does-it-mean-by-command-cd-d-dp0-in-windows/18310053) only, to change both drive and directory at once.
In case PureBasic_Opensource not in the same drive as cmd.exe (%Systemroot%/Windows32)

**Pull request merged**
