### PR TITLE
MemoryViewer 

### PR DESCRIPTION
**Pull request by idle-PB**
Added a button to display data table view values as Dec Hex Oct 
added x64 instructions to AssemblyOperands (yes I know it says it's auto generated but maybe Fred can add these to the compiler) 
added a Linux-x64.sh to build on linux with instructions to get around linking in gtk3, which is perhaps an issue with the current linux 5.71 x64 lts build.

### CODE REVIEW

**Comment by tajmone** [comment]
@idle-PB, if I understand correctly this PR reproposes the contents of PR #39 (which was closed due the base branch issues), and therefore also contains the __BUG FIX__ regarding the Memory Viewer (i.e. display hex in tables when Prefs->Debugger->Individual Settings->Memory Viewer-> Display Hex values is checked)?

**Comment by idle-PB** [comment]
@tajmone, I guess it does, It's just an extension of that fix, I'm still not sure what I'm doing with git yet.

**Comment by fantaisie-software** [comment]
I seen there is a lot of space difference in the files, any chances to clean that ? Also, could you squash all your commit into one, so I can review it ? (also rebase from master to remove the conflict)

**Comment by tajmone** [comment]
The commit is failing the test due to `PureBasicDebugger/MemoryViewer.pb` not passing the EditorConfig validation for code style consistency:

https://travis-ci.com/fantaisie-software/purebasic/builds/147021531

Try running EClint locally to get the full details of what's wrong with that file:

    eclint check

Probably it should be enough to reformat the file using the PB IDE native linter.

Instead of merging `master` into your branch you should rebase and solve the conflicts locally via three-way merge.

**Comment by idle-PB** [comment]
I've got no idea how to sort it out, I just edited the file in github to remove what it said was in conflict which resolved it but then it failed the validation?

**Comment by tajmone** [comment]
> I've got no idea how to sort it out, I just edited the file in github to remove what it said was in conflict which resolved it but then it failed the validation?

They are two different things, the validation pertains code styles consistency and is done via Travis CI and the `validate.sh` script in the repository root (which also checks for IDE settings in PB sources).

In 10 minutes times I should be able to finish aand push a current project and then switch to this one, so I can pull locally all your changes and see what's wrong with the validation.

**Comment by tajmone** [comment]
OK @idle-PB, I've pulled locally your dev branch and realized that the problem with `PureBasicDebugger/MemoryViewer.pb` is that it lacks the UTF-8 BOM.

I see that you've created your changes in `master` branch, so you might struggle rebasing the upstream `master`.

Anyhow, I should make a pull request on your repository soon, which should fix the problems in this PR too once you merge it into your branch.

**Comment by tajmone** [comment]
My PR fixes the Travis CI validation:

https://github.com/idle-PB/purebasic/pull/1

If you accept the PR on your repo, and then push, it should automatically fix the Travis checks here.

Now I'll start looking into the rebase conflicts.

**Comment by idle-PB** [comment]
I just did a stash and pull re edited the file, ran the validation and then tried to push and it didn't like it. 
Why is it so complicated, the file I got back after the pull was full of junk?

**Comment by tajmone** [comment]
> I just did a stash and pull re edited the file, ran the validation and then tried to push and it didn't like it.

Now it clearly states "All checks have passed", so the Travis CI part is solved by my PR.

> Why is it so complicated, the file I got back after the pull was full of junk?

You're confusing the Travis CI build tests and the Git conflicts; they are two different problems, the former is solved, the latter not.

I've been trying to rebase locally your `master` branch, but even after going through three-way-merge conflicts resolution I notice some odd stuff.

I really have to ask you this: did you by any chance carry out files copy-and-paste operations while working on the PB sources?

It's just that I can't make head and tails of the strange conflicts that show up, which seem older than you're master branch base commit date. If you did paste some PB sources taken from other commits, we need to know that, because in this case you should create a new PR altogether, to be on the safe side.

**Comment by tajmone** [comment]
@idle-PB, this is your `master` branch rebased on the upstream `master`:

https://github.com/tajmone/purebasic/tree/idle-PB-rebase-memory-viewer

A few conflicts required choosing whether to take from upstream or from your branch, so you'd probably have to sift carefully through the changed files.

Overall, it seemed that the conflicts pertained mostly to header comments still carrying the Fantaisie Software typo before correction (in you sources, which makes me wonder how date they really are), whereas in the sources actual code the conflicts where mostly due to whitespace differences.

Still, you could try and checkout my rebased branch, test it locally, and if you're happy with it just merge it on your `master` and push.

**Comment by tajmone** [comment]
PS: I've also created a local backup of your current master branch, in case things turn out bad, so the original commits are not lost.

You should never make edits in the master branch of a forked repository, otherwise you have to face all sorts of problems when you need to rebase, since you can't pull anymore the upstream master branch in your repository, due to the divergence introduced by your changes.

**Pull request closed without merging**
