### PR TITLE
Custom Git Hooks for EditorConfig

### PR DESCRIPTION
**Pull request by tajmone**
- Add to the repository scripts to install and remove a custom pre-commit Git hook that will validate all staged files via EClint:

    + `git-hook-install.sh`
    + `git-hook-remove.sh`

    The advantage of the hook (compared to `vaildate.sh`) is that it will only validate the staged changed files, not the whole project folder.
- Add the hook scripts to the export-ignore rules in `.gitattributes`, so they won't be included in the downloadable Zip archive of the project.
- Update [`CONTRIBUTING.md`][CONTRIBUTING.md] with instructions on how to install and use the new Git hook.
- Set to executable some shell scripts that weren't.

[CONTRIBUTING.md]: https://github.com/fantaisie-software/purebasic/blob/EditorConfig-Git-hook/CONTRIBUTING.md#code-styles-validation-of-pull-request "View updated CONTRIBUTING.md in PR branch"

### CODE REVIEW

**Comment by tajmone** [comment]
# Don't Merge Yet!

The hook scripts are incomplete, I should add the PB specific checks for IDE settings in source files and for trailing spaces (allowing spaces only lines).

I only need to adapt some snippets from `validate.sh` and add them to hook-installer script, but tweaked to carry out the checks only on staged files.

When I have some time I'll fix this and do some tests.

**Comment by Naheulf** [comment]
> 
> # Don't Merge Yet!
> 

For that you can also mark the PR as draft PR ;)

**Comment by tajmone** [comment]
> For that you can also mark the PR as draft PR ;)

I can't see that option. Where should I find it?

**Comment by SicroAtGit** [comment]
> > For that you can also mark the PR as draft PR ;)
> 
> I can't see that option. Where should I find it?

[Converting a pull request to a draft](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft)

**Comment by tajmone** [comment]
Thanks for the link @SicroAtGit! I had a vague remembrance of this feature, but forgot how to access it.

**Comment by fantaisie-software** [comment]
Is this pull request still relevent ?

**Comment by tajmone** [comment]
> Is this pull request still relevent ?

Probably not. I'll remove the PR, and just keep the local branch.

**Pull request closed without merging**
