### PR TITLE
Update PureBasic.pb

### PR DESCRIPTION
**Pull request by mk-soft-65**
Fix IDE crash on macOS Big Sur

### CODE REVIEW

**Comment by fantaisie-software** [comment]
I don't have big Sur yet, can someone else test it ?

**Comment by mk-soft-65** [comment]
The problem is actually not the programme from the IDE, but the internal handle of (Wait)WindowEvent in macOS. With a CloseWindow from the main window of the IDE, no more events should run and no callback from the ScintillaGadget with the code #SCN_UPDATEUI should run. But this happens since macOS Big Sur. This leads to a crash when the callback of the ScintillaGadget is called and the history is processed at the same time.

With the adjustment with FlushEvents after a CloseWindow, the problem was solved, but is not eliminated internally.

That the fix works was confirmed here.
Link: https://www.purebasic.fr/english/viewtopic.php?f=24&t=76595

**Comment by mk-soft-65** [comment]
Example code
`
;-TOP

; Constant
Enumeration ;Window
  #Main
EndEnumeration

Enumeration ; Menu
  #Menu
EndEnumeration

Enumeration ; MenuItems
  #MenuExitApplication
EndEnumeration
  
Enumeration ; Gadgets
  #List
EndEnumeration

Enumeration ; Statusbar
  #Status
EndEnumeration

; Global Variable
Global ExitApplication

; Functions
Procedure UpdateWindow()
  
  Protected x, y, dx, dy, menu, status
  
  menu = MenuHeight()
  If IsStatusBar(#Status)
    status = StatusBarHeight(#Status)
  Else
    status = 0
  EndIf
  x = 0
  y = 0
  dx = WindowWidth(#Main)
  dy = WindowHeight(#Main) - menu - status
  ResizeGadget(#List, x, y, dx, dy)
  
EndProcedure

Procedure ScintillaCallBack(Gadget, *scinotify.SCNotification)
  Select *scinotify\nmhdr\code
    Case #SCN_UPDATEUI
      Debug "Scintilla Code #SCN_UPDATEUI: " + *scinotify\nmhdr\code
    Default
      Debug "Scintilla Code: " + *scinotify\nmhdr\code
  EndSelect
  
  ProcedureReturn 0
EndProcedure

; Main
Procedure Main()
  
  Protected event, style
  
  style = #PB_Window_SystemMenu | #PB_Window_MinimizeGadget | #PB_Window_MaximizeGadget | #PB_Window_SizeGadget
  dx = 800
  dy = 600
  
  If OpenWindow(#Main, #PB_Ignore, #PB_Ignore, dx, dy, "Main", style)
    
    ; Menu
    CreateMenu(#Menu, WindowID(#Main))
    MenuTitle("Ablage")
    MenuItem(#MenuExitApplication, "Be&enden")
    ; Gadgets
    ;ListViewGadget(#List, 0, 0, dx, dy)
    ScintillaGadget(#List, 0, 0, dx, dy, @ScintillaCallback())
    
    ; Statusbar
    CreateStatusBar(#Status, WindowID(#Main))
    AddStatusBarField(#PB_Ignore)
    
    UpdateWindow()
    
    BindEvent(#PB_Event_SizeWindow, @UpdateWindow(), #Main)
    
    ; Main Loop
    Repeat
      event = WaitWindowEvent()
      Select event
        Case #PB_Event_Menu
          Select EventMenu()
            CompilerIf #PB_Compiler_OS = #PB_OS_MacOS   
              Case #PB_Menu_About
                
              Case #PB_Menu_Preferences
                
              Case #PB_Menu_Quit
                ExitApplication = #True
                
            CompilerEndIf
              
            Case #MenuExitApplication
              ExitApplication = #True
              
          EndSelect
          
        Case #PB_Event_Gadget
          Select EventGadget()
            Case #List
              
          EndSelect
          
        Case #PB_Event_CloseWindow
          Select EventWindow()
            Case #Main
              ExitApplication = #True
              
          EndSelect
          
      EndSelect
      
    Until ExitApplication
    
  EndIf
  
EndProcedure : Main()

Debug "FreeGadget"
;FreeGadget(#List)

Debug "Close Window"
CloseWindow(#Main)
Debug "End"

Delay(500)

End
`
Debug output since Big Sur
`
Scintilla Code #SCN_UPDATEUI: 2007
Scintilla Code: 2013
Scintilla Code: 2013
Scintilla Code: 2013
Scintilla Code: 2013
Scintilla Code: 2013
Scintilla Code: 2013
FreeGadget
Close Window
Scintilla Code #SCN_UPDATEUI: 2007
End
`

**Comment by kenmo-pb** [comment]
Since this commit (`FlushEvents` after `CloseWindow`) I get a debugger error every time I close the IDE: _"At least one window should be opened to use this command"_ on `DispatchEvent(WindowEvent())`. I'm on Windows.

Does anyone get this error on Mac or Linux? If just Windows: should we wrap the new `FlushEvents()` in a `CompilerIf` check to avoid the error?

**Pull request merged**
