### PR TITLE
Update project PBP file to use renamed files

### PR DESCRIPTION
**Pull request by kenmo-pb**
Three files were recently renamed (PR #56).

This new PR updates the references in the PBP project file to the new names.

### CODE REVIEW

**Comment by tajmone** [comment]
I noticed that you've renamed the proj. file inserting a space:

- `PureBasicIDE.pbp` &rarr; `PureBasic IDE.pbp`

Spaces in files names are best avoided in repositories, for they might complicate automation scripts on some OSs.

**Comment by kenmo-pb** [comment]
I'm not sure why you think that... I didn't rename it, it has had a space the whole time.

Original source from December:  
https://github.com/fantaisie-software/purebasic/tree/9b11a750c387dd85fcd94dc41094e35f2cdaf960/PureBasicIDE

**Comment by tajmone** [comment]
> I'm not sure why you think that... I didn't rename it, it has had a space the whole time.

Sorry, my fault! I misinterpreted the WebUI (due to tiredness).

I suggest then renaming the proj. file and either replacing the space with an underscore or hyphen, or just remove it.

**Comment by fantaisie-software** [comment]
Perfect.

**Pull request merged**
