### PR TITLE
Fix Gadgets Drag n Drop Position  in FormDesigner

### PR DESCRIPTION
**Pull request by ChrisRfr**
Fix Gadgets Offset with Drag n Drop in FormDesigner
Place the Gadget on the mouse position using the same alignment FD_AlignPoint() as in FD_Move() with topwinpadding, leftpadding, Page_Padding...

### CODE REVIEW

**Comment by SicroAtGit** [comment]
Your commit message says little about your change. For examples look at the other commits.

**Comment by ChrisRfr** [comment]
Sorry not to be clear. 
It's probably best to be able to reproduce
Create a New Form and from the Form Toolbox Panel, drag and Drop a Button on the drawn window (Window_0).
The button is created on the window but not at the right position. I mean the mouse position.
It is moved to the right and down. 

The position calculation does not take into account:
the space on the left and top of the drawn window = #Page_Padding
the left and top borders of the window = leftpadding and topwinpadding
The height of the menu and toolbar, if added = toptoolpadding - topmenupadding
The position following the scrollbars = FormWindows()\paddingx FormWindows()\paddingy

To have the right Gadget alignment, the calculation must be done as it is in the FD_Move() procedure.
with
d_x1 = FD_AlignPoint(d_x1 + FormWindows()\paddingx - #Page_Padding - leftpadding)
d_y1 = FD_AlignPoint(d_y1 + FormWindows()\paddingy - #Page_Padding - topwinpadding - toptoolpadding - topmenupadding)
And not just:
d_x1 = FD_AlignPoint(d_x1)
d_y1 = FD_AlignPoint(d_y1)

**Comment by ChrisRfr** [comment]
@SicroAtGit
Sorry but I don't know how to rename the commit message on Github Desktop or Web
I don't find it, it's a labyrinth

**Comment by tajmone** [comment]
GitHub Desktop doesn't have that feature, so you'll have to manually amend the commit:

https://stackoverflow.com/questions/10728420/editing-the-git-commit-message-in-github#41513487

**Comment by SicroAtGit** [comment]
@ChrisRfr 

Thanks, now your PR is more understandable without looking into the code and understanding the changes.

The only thing missing is the adjustment of the commit message, because "Update mainevents.pb" can mean many things. "Fix Gadgets Drag n Drop Position in FormDesigner" is better for the commit message title. As commit message body text, it's best to describe why you made this change. In addition, you can also point out side effects caused by the change, for example.

Here's a good description of how best to write a commit message:
https://chris.beams.io/posts/git-commit/

> GitHub Desktop doesn't have that feature

Yes, GitHub Desktop is quite simple and lacks some features. Also, the GitHub website does not offer that.

**Comment by ChrisRfr** [comment]
If it is really annoying, can you adjust the commit message for me, please 
After GitHub desktop, I'd have to install Git now, it's very confusing...

**Comment by SicroAtGit** [comment]
@ChrisRfr 
If you add me as a collaborator on your fork repository, I can adjust your commit message:
https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/inviting-collaborators-to-a-personal-repository

**Comment by tajmone** [comment]
> If you add me as a collaborator on your fork repository, I can adjust your commit message:

The easiest way Sicro is to add his fork to your remotes, pull his PR branch, amend the commit and create a PR on his fork.

**Comment by tajmone** [comment]
@ChrisRfr:

> After GitHub desktop, I'd have to install Git now, it's very confusing...

Yes, **GitHub Desktop** no longer includes a full Git shell (see: desktop/desktop#340).

Installing Git along with any Git GUI is strongly recommended anyhow (even if the GUI includes and embedded Git shell) — especially under Windows, because it includes a full Bash for Windows with all the \*nix command line tools that are commonly required in the Git workflow.

It's not uncommon to have multiple Git shells installed on the same machine due to Git GUI installing their own embedded Git (if you use multiple Git front-ends, you might end up with three or four Git installations). As a general guideline, you should always use the official Git package for command line operations, because it guarantees to include all the latest Git features and bug fixes, whereas embedded Git versions that ship with GUIs aren't always up-to-date, nor feature-complete.

Usually, the embedded Git shells that are included with Git GUIs are intended to supply a simple command line interface to allow users to carry out common Git operations not covered by the GUI application, whereas the full Git package aims to provide a full working environment. For example, some Git GUIs for Windows will only make Git available via the CMD, without installing Bash.

**Comment by ChrisRfr** [comment]
@SicroAtGit 
I sent you an invitation. It's the world upside down, but it's nice to have you as a collaborator

**Comment by ChrisRfr** [comment]
@tajmone 
Thanks for your information
I understand that Git is a powerful collaborative tool with its own command language
But it's probably developed by guys too much in their git space. They forgot about simplicity and user-friendliness.
A new one, like me, has to twist his mind to get in. Once the mind twisted, it should be simpler and more logical.

**Comment by SicroAtGit** [comment]
> The easiest way Sicro is to add his fork to your remotes, pull his PR branch, amend the commit and create a PR on his fork.

Yes, that would probably have worked, too. I was not so sure that amending commits by pull request would work, so I suggested the Collaborator variation.

> @SicroAtGit
> I sent you an invitation. It's the world upside down, but it's nice to have you as a collaborator

Thanks. I have improved your commit message.

**Comment by tajmone** [comment]
@ChrisRfr:

> I understand that Git is a powerful collaborative tool with its own command language
> But it's probably developed by guys too much in their git space. They forgot about simplicity and user-friendliness.

Welcome to the Git-haters club! I've even come across a website entirely dedicated to Git-hating, where you could sign the haters' guest list and mention what you hate most about Git (can't find the link anymore).

> A new one, like me, has to twist his mind to get in. Once the mind twisted, it should be simpler and more logical.

One of the most famous Git books is titled _[Git for Humans](https://abookapart.com/products/git-for-humans)_, which says it all.

A famous web-designer during a prize-award interviewed stated that "the Internet is like a toilet, every office needs it". Git is the same, we need it, but we don't need to love it. When you look at version control tools like [Fossil](https://fossil-scm.org/home/doc/trunk/www/index.wiki), it makes you wonder why some developers choose complexity over simplicity as a design principle.

Anyhow, you'll find many ironic articles on Git, which can allow us to at least laugh in the face of the daily horrors we have to subject ourselves to:

- http://www.evan.org/Fun/Git/index.htm

**Comment by fantaisie-software** [comment]
Looks good, thanks !

**Comment by SicroAtGit** [comment]
Unfortunately, my improvement to the commit message was overwritten. :unamused:

**Comment by tajmone** [comment]
> Unfortunately, my improvement to the commit message was overwritten. 

That's the cool thing about merging directly into `master` — every merge is final, no amends permitted! 😉

**Comment by kenmo-pb** [comment]
Maybe after 5.72 is released we can all start using a `dev` branch properly, and only use `master` for releases.

**Pull request merged**
